version: '3.7'
services:
  db:
    image: postgres:11
    restart: always
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/db